# TCL File Generated by Component Editor 18.1
# Thu Apr 25 22:34:17 BST 2024
# DO NOT MODIFY


# 
# avl_export "avl_export" v1.0
#  2024.04.25.22:34:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avl_export
# 
set_module_property DESCRIPTION ""
set_module_property NAME avl_export
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avl_export
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avl_export
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avl_export.sv SYSTEM_VERILOG PATH avl_export.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter pADDR_WIDTH STRING 8
set_parameter_property pADDR_WIDTH DEFAULT_VALUE 8
set_parameter_property pADDR_WIDTH DISPLAY_NAME pADDR_WIDTH
set_parameter_property pADDR_WIDTH TYPE STRING
set_parameter_property pADDR_WIDTH UNITS None
set_parameter_property pADDR_WIDTH HDL_PARAMETER true
add_parameter pDATA_WIDTH STRING 32
set_parameter_property pDATA_WIDTH DEFAULT_VALUE 32
set_parameter_property pDATA_WIDTH DISPLAY_NAME pDATA_WIDTH
set_parameter_property pDATA_WIDTH TYPE STRING
set_parameter_property pDATA_WIDTH UNITS None
set_parameter_property pDATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk
set_interface_property avs associatedReset rst
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs s_avl_addr address Input pADDR_WIDTH
add_interface_port avs s_avl_wrena write Input 1
add_interface_port avs s_avl_wrdata writedata Input pDATA_WIDTH
add_interface_port avs s_avl_rdena read Input 1
add_interface_port avs s_avl_rddata readdata Output pDATA_WIDTH
add_interface_port avs s_avl_wrq waitrequest Output 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk avl_clock clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst avl_rst_n reset_n Input 1


# 
# connection point int
# 
add_interface int interrupt end
set_interface_property int associatedAddressablePoint avs
set_interface_property int associatedClock clk
set_interface_property int associatedReset rst
set_interface_property int bridgedReceiverOffset ""
set_interface_property int bridgesToReceiver ""
set_interface_property int ENABLED true
set_interface_property int EXPORT_OF ""
set_interface_property int PORT_NAME_MAP ""
set_interface_property int CMSIS_SVD_VARIABLES ""
set_interface_property int SVD_ADDRESS_GROUP ""

add_interface_port int s_avl_irq irq Output 1


# 
# connection point cond
# 
add_interface cond conduit end
set_interface_property cond associatedClock clk
set_interface_property cond associatedReset rst
set_interface_property cond ENABLED true
set_interface_property cond EXPORT_OF ""
set_interface_property cond PORT_NAME_MAP ""
set_interface_property cond CMSIS_SVD_VARIABLES ""
set_interface_property cond SVD_ADDRESS_GROUP ""

add_interface_port cond m_avl_clk clk Output 1
add_interface_port cond m_avl_rstn rstn Output 1
add_interface_port cond m_avl_addr adr Output pADDR_WIDTH
add_interface_port cond m_avl_wrdata wdata Output pDATA_WIDTH
add_interface_port cond m_avl_rdena rdena Output 1
add_interface_port cond m_avl_rddata rdata Input pDATA_WIDTH
add_interface_port cond m_avl_irq irq Input 1
add_interface_port cond m_avl_wrq wrq Input 1
add_interface_port cond m_avl_wrena wrena Output 1

