# TCL File Generated by Component Editor 18.1
# Thu Apr 25 22:34:45 BST 2024
# DO NOT MODIFY


# 
# eth_ip_core_export "eth_ip_core_export" v1.0
# xkent 2024.04.25.22:34:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module eth_ip_core_export
# 
set_module_property DESCRIPTION ""
set_module_property NAME eth_ip_core_export
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR xkent
set_module_property DISPLAY_NAME eth_ip_core_export
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eth_ip_core_export
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eth_ip_core_export.sv SYSTEM_VERILOG PATH eth_ip_core_export.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter pADDR_CNTRL_WIDTH STRING 8
set_parameter_property pADDR_CNTRL_WIDTH DEFAULT_VALUE 8
set_parameter_property pADDR_CNTRL_WIDTH DISPLAY_NAME pADDR_CNTRL_WIDTH
set_parameter_property pADDR_CNTRL_WIDTH TYPE STRING
set_parameter_property pADDR_CNTRL_WIDTH UNITS None
set_parameter_property pADDR_CNTRL_WIDTH HDL_PARAMETER true
add_parameter pADDR_TIMEST_WIDTH STRING 8
set_parameter_property pADDR_TIMEST_WIDTH DEFAULT_VALUE 8
set_parameter_property pADDR_TIMEST_WIDTH DISPLAY_NAME pADDR_TIMEST_WIDTH
set_parameter_property pADDR_TIMEST_WIDTH TYPE STRING
set_parameter_property pADDR_TIMEST_WIDTH UNITS None
set_parameter_property pADDR_TIMEST_WIDTH HDL_PARAMETER true
add_parameter pDATA_WIDTH STRING 32
set_parameter_property pDATA_WIDTH DEFAULT_VALUE 32
set_parameter_property pDATA_WIDTH DISPLAY_NAME pDATA_WIDTH
set_parameter_property pDATA_WIDTH TYPE STRING
set_parameter_property pDATA_WIDTH UNITS None
set_parameter_property pDATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk avl_clock clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst avl_rst_n reset_n Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk
set_interface_property avs associatedReset rst
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs s_cntrl_avl_addr address Input pADDR_CNTRL_WIDTH
add_interface_port avs s_cntrl_avl_wrena write Input 1
add_interface_port avs s_cntrl_avl_wrdata writedata Input pDATA_WIDTH
add_interface_port avs s_cntrl_avl_rdena read Input 1
add_interface_port avs s_cntrl_avl_rddata readdata Output pDATA_WIDTH
add_interface_port avs s_cntrl_avl_wrq waitrequest Output 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point int
# 
add_interface int interrupt end
set_interface_property int associatedAddressablePoint avs
set_interface_property int associatedClock clk
set_interface_property int associatedReset rst
set_interface_property int bridgedReceiverOffset ""
set_interface_property int bridgesToReceiver ""
set_interface_property int ENABLED true
set_interface_property int EXPORT_OF ""
set_interface_property int PORT_NAME_MAP ""
set_interface_property int CMSIS_SVD_VARIABLES ""
set_interface_property int SVD_ADDRESS_GROUP ""

add_interface_port int s_cntrl_avl_irq irq Output 1


# 
# connection point cond_cntrl
# 
add_interface cond_cntrl conduit end
set_interface_property cond_cntrl associatedClock clk
set_interface_property cond_cntrl associatedReset rst
set_interface_property cond_cntrl ENABLED true
set_interface_property cond_cntrl EXPORT_OF ""
set_interface_property cond_cntrl PORT_NAME_MAP ""
set_interface_property cond_cntrl CMSIS_SVD_VARIABLES ""
set_interface_property cond_cntrl SVD_ADDRESS_GROUP ""

add_interface_port cond_cntrl m_cntrl_avl_clk clk Output 1
add_interface_port cond_cntrl m_cntrl_avl_rstn rstn Output 1
add_interface_port cond_cntrl m_cntrl_avl_addr adr Output pADDR_CNTRL_WIDTH
add_interface_port cond_cntrl m_cntrl_avl_wrena wrena Output 1
add_interface_port cond_cntrl m_cntrl_avl_wrdata wdata Output pDATA_WIDTH
add_interface_port cond_cntrl m_cntrl_avl_rdena rdena Output 1
add_interface_port cond_cntrl m_cntrl_avl_rddata rdata Input pDATA_WIDTH
add_interface_port cond_cntrl m_cntrl_avl_irq irq Input 1
add_interface_port cond_cntrl m_cntrl_avl_wrq wrq Input 1


# 
# connection point avm
# 
add_interface avm avalon start
set_interface_property avm addressUnits WORDS
set_interface_property avm associatedClock clk
set_interface_property avm associatedReset rst
set_interface_property avm bitsPerSymbol 8
set_interface_property avm burstOnBurstBoundariesOnly false
set_interface_property avm burstcountUnits WORDS
set_interface_property avm doStreamReads false
set_interface_property avm doStreamWrites false
set_interface_property avm holdTime 0
set_interface_property avm linewrapBursts false
set_interface_property avm maximumPendingReadTransactions 0
set_interface_property avm maximumPendingWriteTransactions 0
set_interface_property avm readLatency 0
set_interface_property avm readWaitTime 0
set_interface_property avm setupTime 0
set_interface_property avm timingUnits Cycles
set_interface_property avm writeWaitTime 0
set_interface_property avm ENABLED true
set_interface_property avm EXPORT_OF ""
set_interface_property avm PORT_NAME_MAP ""
set_interface_property avm CMSIS_SVD_VARIABLES ""
set_interface_property avm SVD_ADDRESS_GROUP ""

add_interface_port avm m_dma_avl_addr address Output 32
add_interface_port avm m_dma_avl_rdena read Output 1
add_interface_port avm m_dma_avl_rddata readdata Input 64
add_interface_port avm m_dma_avl_wrena write Output 1
add_interface_port avm m_dma_avl_wrdata writedata Output 64
add_interface_port avm m_dma_avl_wrq waitrequest Input 1
add_interface_port avm m_dma_avl_rddataval readdatavalid Input 1
add_interface_port avm m_dma_avl_burst_cnt burstcount Output 8


# 
# connection point cond_dma
# 
add_interface cond_dma conduit end
set_interface_property cond_dma associatedClock clk
set_interface_property cond_dma associatedReset rst
set_interface_property cond_dma ENABLED true
set_interface_property cond_dma EXPORT_OF ""
set_interface_property cond_dma PORT_NAME_MAP ""
set_interface_property cond_dma CMSIS_SVD_VARIABLES ""
set_interface_property cond_dma SVD_ADDRESS_GROUP ""

add_interface_port cond_dma s_dma_avl_addr addres Input 32
add_interface_port cond_dma s_dma_avl_rdena read Input 1
add_interface_port cond_dma s_dma_avl_wrena write Input 1
add_interface_port cond_dma s_dma_avl_rddata readdata Output 64
add_interface_port cond_dma s_dma_avl_wrdata writedata Input 64
add_interface_port cond_dma s_dma_avl_wrq waitrequest Output 1
add_interface_port cond_dma s_dma_avl_rddataval readdatavalid Output 1
add_interface_port cond_dma s_dma_avl_burst_cnt burstcount Input 8

